"""rm_dehom.py -- the GENERAL OpenSG-RM dehomogenizer for ONE station, and
the shared core every other recovery script imports.

    input    1dsg.yaml            the 1-D SG line mesh (the only file input)
             FF DATA IN THE CODE  the section resultants driving the recovery
                                  -- edit the USER INPUT block below
    output   <sg>_dehom.SM/.EM/.U the 3-D stress / strain / displacement
                                  ALONG THE 1-D SG (Gauss depths by default)
             <sg>_dehom.vtk       generated BY DEFAULT from the same arrays

Run:  python rm_dehom.py

THE CHAIN.  The homogenization is re-run on the SG line (rm_plate_msg solves
the nodal warping ladders V0 / V11 / V12 in milliseconds), the FF data is
converted to plate strains through the freshly inverted A6, and the recovery
is evaluated at the SG element GAUSS DEPTHS -- the nodal fluctuation solution
reaching them through its own quartic shape functions, w(z_g) = N(z_g) @
w_nodes.  Every output depth is strictly inside one ply, so ply-interface
double values never appear in the files.

WHAT "FF DATA" MEANS HERE: the plate section resultants at the station,
    F6  = [N11, N22, N12, M11, M22, M12]     [N/m, N]
    Q2v = [Q1, Q2]                           transverse shears [N/m]
exactly what a shell solution (or a beam FF file mapped to the wall) hands
the recovery.  Gradients of the strains and the surface-pressure ladder are
OPTIONAL refinements -- zero them for a pure constant-resultant dehom.

The Abaqus whole-plate version of this -- parse a field .dat, build the same
drivers at every node/Gauss station, jax.vmap THIS file's operators over all
of them -- is rm_dehom_dat.py, which imports everything below.

# ----------------------------------------------------------------------------
# ALL VARIABLES USED IN THIS SCRIPT
# ----------------------------------------------------------------------------
# USER INPUT block
#   SG_YAML      the 1-D SG mesh file
#   F6, Q2v      the FF data: 6 resultants + 2 transverse shears
#   DE1, DE2     optional in-plane gradients of the 6 plate strains
#   D11, D12, D22   optional second gradients
#   QT6          optional surface-load ladder [q, q,1, q,2, q,11, q,12, q,22]
#   LATTICE      "gauss" (default) or "nodes" -- the through-thickness stations
#
# core (importable)
#   load_sg(sg_yaml)          -> dict: inp, r, S6, H, OFF, ZNODE, NPE, NEL
#   z_stations(sg, lattice)   -> the output depths ZS in the SG frame
#   build_ops(r, z_sg)        -> TE, TS, TW: (nz, 6|3, 42) strain / stress /
#                                warping operators from 42 unit drivers
#   assemble_driver(...)      -> the 42-vector [E6 dE1 dE2 d11 d12 d22 qt6]
#   material_rotations(sg,ZS) -> (Rs, Re) per-depth laminate -> ply-material
#                                rotation matrices (apply AFTER the rescale)
#   write_field(path, ...)    the .SM/.EM/.U text writer (x y z + components)
#   write_vtk(path, ...)      structured-grid VTK from the same arrays;
#                             handles a single-station 1 x 1 x nz line too
#   SGIDX, ORDER              SG Voigt positions and the printed order
#
# main-block working set
#   sg           the load_sg dict;  ZS, NZS  the depths and their count
#   E6           S6 @ F6, the plate strains of the FF data
#   D            the 42-driver vector;  TE, TS, TW  the operators
#   Eps, Sig     (1, nz, 6) recovered strain and stress
#   Warp, U      (1, nz, 3) warping and total displacement (u0 = 0 here:
#                a single station has no plate solution to add)
#   stem         output basename, <SG_YAML stem>_dehom
# ----------------------------------------------------------------------------
"""
import os
import sys

import numpy as np
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
try:
    import opensg_solid                      # pip install -e . -- nothing to do
except ImportError:                          # fall back to the in-repo source tree
    ROOT = HERE
    while not os.path.isdir(os.path.join(ROOT, "src", "opensg_solid")):
        parent = os.path.dirname(ROOT)
        if parent == ROOT:                   # hit the filesystem root
            raise ImportError(
                "opensg_solid not installed and no src/ found above " + HERE)
        ROOT = parent
    sys.path.insert(0, os.path.join(ROOT, "src"))

from opensg_solid.rm_plate_1D.segment_plate import read_plate_sg_yaml
from opensg_solid.rm_plate_1D.msg_rm_plate import (rm_plate_msg,
                                            msgrm_strain_at_depth,
                                            msgrm_warping_at_depth)

# THE CORE NOW LIVES IN rm_plate.rm_dehom (promoted there because
# nothing in it is example-specific).  This file keeps the ex5-local imports
# working (rm_dehom_dat.py does rom rm_dehom import ...) and carries the
# single-station USER-INPUT dehom below.
from opensg_solid.rm_plate_1D.rm_dehom import (SGIDX, ORDER, load_sg, z_stations,
                                        build_ops, assemble_driver,
                                        material_rotations, mls_gradients,
                                        write_field, write_vtk)

# ---- the single-station dehom ----------------------------------------------
if __name__ == "__main__":
    import time as _t
    print("start: " + _t.strftime("%Y-%m-%d %H:%M:%S"))
    # ------------------------- USER INPUT ------------------------------------
    SG_YAML = os.path.join(HERE, "1dsg.yaml")
    # FF data: the section resultants at the station.  NO defaults -- these
    # are YOURS.  The script refuses to run until both are set.
    F6 = None                     # [N11, N22, N12, M11, M22, M12]  [N/m, N]
    Q2v = None                    # [Q1, Q2]  [N/m]  (drives the rescale)
    # optional refinements -- None means zero; a bare FF gives the classical
    # ply stresses (s11/s22/s12) and NO transverse shear or s33.  A SINGLE
    # FF fixes no gradients (the equilibrium closure is REMOVED -- it is
    # indeterminate); gradients come ONLY from finite differences of an FF
    # FIELD (a station line or a 2-D lattice: rm_dehom_dat.py), or from a
    # known analytical mode.  Details: dehom_README.md.
    DE1 = DE2 = None              # d(E6)/dx, d(E6)/dy
    D11 = D12 = D22 = None        # second gradients
    QT6 = None                    # surface-load ladder [q q,1 q,2 q,11 q,12 q,22]
    LATTICE = "gauss"             # "gauss" (default) or "nodes"
    # -------------------------------------------------------------------------

    if F6 is None or Q2v is None:
        raise ValueError(
            "FF data not given. Set it in the USER INPUT block first:\n"
            "  F6  = [N11, N22, N12, M11, M22, M12]   # [N/m, N]\n"
            "  Q2v = [Q1, Q2]                          # [N/m]\n"
            "There are deliberately no defaults: the FF is the user's input, "
            "and a built-in number would silently masquerade as a result.")
    if len(F6) != 6 or len(Q2v) != 2:
        raise ValueError("F6 must have 6 entries and Q2v 2, got %d and %d"
                         % (len(F6), len(Q2v)))

    sg = load_sg(SG_YAML)
    ZS = z_stations(sg, LATTICE)
    NZS = len(ZS)
    print("homo re-run: %d plies, %d-noded elements -> %d %s depths"
          % (len(sg["inp"]["thick"]), sg["NPE"], NZS, LATTICE))

    E6 = sg["S6"] @ np.asarray(F6, float)
    D = assemble_driver(E6, DE1, DE2, D11, D12, D22, QT6)
    TE, TS, TW = build_ops(sg["r"], ZS)
    Eps = (TE @ D)[None]                          # (1, nz, 6)
    Sig = (TS @ D)[None]
    Warp = (TW @ D)[None]

    # transverse-shear consistency: carry the given Q1/Q2 if any are nonzero
    if any(abs(q) > 0 for q in Q2v):
        zf = np.linspace(-sg["H"] / 2 + 1e-9, sg["H"] / 2 - 1e-9, 61)
        _, TSf, _ = build_ops(sg["r"], zf + sg["OFF"])
        Sf = TSf @ D
        for col, q in ((4, Q2v[0]), (3, Q2v[1])):
            I = np.trapezoid(Sf[:, col], zf)
            if abs(I) > 1e-12:
                Sig[:, :, col] *= q / I

    # ply MATERIAL frame for the delivered fields (rotate AFTER the rescale;
    # sigma33 invariant, displacement stays global)
    Rs, Re = material_rotations(sg, ZS)
    Sig = np.einsum("zab,nzb->nza", Rs, Sig)
    Eps = np.einsum("zab,nzb->nza", Re, Eps)

    # a single station has no plate solution: U is the warping alone
    U = Warp.copy()

    stem = os.path.splitext(SG_YAML)[0] + "_dehom"
    lat = ("the %d SG-element Gauss depths" % NZS if LATTICE == "gauss"
           else "the %d SG nodes" % NZS)
    title = "OpenSG-RM single-station dehom of %s" % os.path.basename(SG_YAML)
    write_field(stem + ".SM", "S", "Pa", Sig, [0.0], [0.0], ZS, lat, title)
    write_field(stem + ".EM", "E", "-", Eps, [0.0], [0.0], ZS, lat, title)
    write_field(stem + ".U", "U", "m", U, [0.0], [0.0], ZS, lat, title)
    # the VTK is part of the default output, not an extra step
    write_vtk(stem + ".vtk", [0.0], [0.0], ZS,
              U.reshape(1, 1, NZS, 3), Sig.reshape(1, 1, NZS, 6), title)
    print("wrote %s.SM / .EM / .U / .vtk  (%d depths)"
          % (os.path.basename(stem), NZS))
    for nm in ORDER:
        print("  max|S%s| = %.4e Pa" % (nm, np.abs(Sig[0, :, SGIDX[nm]]).max()))
    print("end:   " + _t.strftime("%Y-%m-%d %H:%M:%S"))
