name: Build and Deploy Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    name: Build the documentation with Sphinx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.11"
          activate-environment: opensg_env
          environment-file: environment.yml
          
      - name: Install documentation dependencies
        shell: bash -l {0}
        run: |
          pip install -r docs/requirements.txt
          
      - name: Build documentation
        shell: bash -l {0}
        run: |
          cd docs
          make html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_build/html'
  deploy:
    name: Deploy documentation to GitHub Pages
    needs: build
    # Sets permissions of the GITHUB_TOKEN to allow deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
      