name: run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      # Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: false

      - name: Install system dependencies for gmsh
        run: |
          sudo apt-get update
          sudo apt-get install -y libopengl0 libgl1-mesa-dri libglu1-mesa-dev

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          miniconda-version: "latest"

      - name: Create environment from lock file
        run: |
          conda create --name test --file conda-linux-64.lock -y
          conda run -n test pip install gmsh==4.15.0
          conda run -n test pip install -e .

      - name: Check environment
        run: |
          conda run -n test conda list

      - name: Run tests
        run: |
          conda run -n test python -c "import opensg"
          conda run -n test pip install pytest
          conda run -n test pytest tests/ -m "not time_consuming" --ignore=tests/test_examples.py
