name: run tests

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      # Step 1: Checkout your code
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          # python-version: "3.9" # setup-miniconda seems to ignore this setting.
          auto-activate-base: false
      - name: Check environmnet
        run: |
          conda info
          conda list
      - name: Run tests
        run: |
          python -c "import opensg"
          pip install pytest
          pytest opensg/tests/
